site_name: æternity JavaScript SDK
repo_url: 'https://github.com/aeternity/aepp-sdk-js'
edit_uri: ''

theme:
  name: readthedocs
  custom_dir: tooling/docs/overrides
  language: en

nav:
  - index.md
