# here I eliminated nestings that are too deep and cause UI issues, for testing

#  - Test1:    <---- Graphical Category (big dark grey)
#    - Test2: deletemetest.md    <------ white foldable title nav entry, NEEDS to link to a file with the rest of the structure ! 
#                                         Here create a file named after the title (e.g. "Test2.md") and put all the linked children from under this topic there!
#                                         As information input, take the hand-made nav config from the current mkdocs.yml, and later create one that consists only of
#                                         created files ! 

site_name: Aeternity JavaScript SDK
plugins:
  - search
#  - mkdocs-simple-hooks:
#      hooks:
#        on_pre_build: "docs.hooks:pre_build"
repo_url: 'https://github.com/aeternity/aepp-sdk-js'

theme:
  name: readthedocs

nav:
  - Overview: README.md
  - guides/quick-start.md
  - Guides:
    - guides/contract-events.md
    - guides/oracle-usage.md
    - guides/aens-usage.md
    - guides/contract-aci-usage.md
    - guides/delegate-signature-to-contract.md
    - Wallet Api: guides/how-to-build-aepp-using-new-wallet-api.md
    - Building Wallets: guides/how-to-build-an-wallet-app-or-extension.md
    - guides/low-vs-high-usage.md
    - guides/import-tree-shaking.md
    - Migration: 
      - guides/migration/migration-7.0.0.md
  - API Reference:
    - account: api/account.md

    - ae: 
      - api/ae/aens.md

    - chain: 
      - api/chain.md
    - channel: api/channel/index.md
    - contract: api/contract/aci.md

    - oracle: api/oracle.md

    - Deprecated RPC Client: api/rpc/client.md
    - tx: api/tx/builder.md

    - Aepp Wallet Communication: api/utils/aepp-wallet-communication/connection.md


    - utils: api/ae.md

  - Examples:
    - NodeJS: guides/import-nodejs.md

    - JS: guides/import-script-tag.md
  - Test1: 
    - Test2: deletemetest.md